repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-build
- repo: https://github.com/golangci/golangci-lint
  rev: v1.41.1
  hooks:
    - id: golangci-lint
- repo: local
  hooks:
    - id: make-test
      name: 'make test'
      entry: make test
      files: '\.go$'
      language: 'system'
      description: "Runs `make test`, requires golang"
